[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "9904fb1b772ab99d1ce285e9add90c44dede2d90"
os = "macos"

    [[aws_c_http_jq.download]]
    sha256 = "153c40233d36da6df6e26b33c866a97d8e447cf82690c7f4f92ac492f238cd13"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.aarch64-apple-darwin.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "f46cb32a0f8b45b91eb9841506e8fffed3293567"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "9ac0134a714cc7cf2b6a9f0c7df4cc41f27c0bdd71b32a3c85b0456a2403f199"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.aarch64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "6a44dc9e189f345f1410408e0ec9268a24edcae4"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "35fe776205a707e48e922a5fd56c084b2dc412135427f15fb22e45caef321377"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.aarch64-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "5999a0d71d38760cb1a969951aee507d25e57dca"
os = "freebsd"

    [[aws_c_http_jq.download]]
    sha256 = "f0b9ea6c793809bb7248082b9a978651469bbb0cbc554fc3782b030b8bbeafbf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.aarch64-unknown-freebsd.tar.gz"
[[aws_c_http_jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "128046f7cc26831d4262c3427f28a51b7aadedeb"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "3f325d9c86892eb99a6b7cfe80f8a760c76ee17af79e9fd6fbb991876f14a436"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "91d206b7429c4bd2c5efa5806927b0241dc32128"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "0de1a5efb57f5db49982ae74ac437d2d1d8697275bebb9806ddb609f08526814"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.armv6l-linux-musleabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "680f9bfedf57801aaaf32b319c277b6577d93799"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "d95771f22bded5db05757b05b6fba8dd95d02ac775433c41e60b1a45cbdfac1c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "daa2774f4ad1dfdadd888fdc19c402b68d797388"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "67ae844c4c6e351968c00a5870b64ab1eb4677912e4f445169f1b1190b4a371b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.armv7l-linux-musleabihf.tar.gz"
[[aws_c_http_jq]]
arch = "i686"
git-tree-sha1 = "a40661a1fbc5eba66749bc5faae5585cefd74566"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "19ea90c440ab376cd703bf8dbf42f161c7aadf358795f3b17196796b7fde8d58"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.i686-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "i686"
git-tree-sha1 = "f629e836a21ad26740c44d92063016af3bf71b89"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "0c7d1cb08961f368a3b993626b7545c261bec11b017bd35df37ba0eab0f928e1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.i686-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "powerpc64le"
git-tree-sha1 = "9920fd7ab334f6810b325e06f17ac2a00ec43a4a"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "e92fd62e92b9529c7b357b30cd3a18683d291e2e7fb56ecaf9a0b3928928475d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.powerpc64le-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "riscv64"
git-tree-sha1 = "22bc46059b609310043b8b3bdbaa46b07c72cc5d"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "ae9073ad9a2c8e852c57bbbc77ae7e59ece22bfebb38f9941cb5f6d7812c466c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.riscv64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "77e2a37dc67389ff76cd63f4c7d4fd97adfb592f"
os = "macos"

    [[aws_c_http_jq.download]]
    sha256 = "5b830acd96a7ede566d0ab86cec660b8e83233675cb0e589059c15631f66744d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.x86_64-apple-darwin.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "f05f6ab4d26fc5ab8162770a5181d4b54acf7d85"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "d2d82b64e52b1369cf186a3286f4aa41a508acc609a7231943fa812912745fbe"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.x86_64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "94132d8a0521506ebe7d647f5bd69fdefb56b042"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "2e841857cd94475be555d61f8a5dc26d3d20dbe8a64fc81412392a4e17c7e60d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.x86_64-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "056c0a9db3bd8de13438be325549f4bbe9d63afe"
os = "freebsd"

    [[aws_c_http_jq.download]]
    sha256 = "89b4946cfd60e470f51cd4cff8dc234668387b830e6496a7ddffc4a9503ac812"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.x86_64-unknown-freebsd.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "6c3ccce0c021a0833d801186a01ac87b87e19a10"
os = "windows"

    [[aws_c_http_jq.download]]
    sha256 = "ce4769d048d2d9cf5d40a8d5b2f55dc1737333e787d5225e5941e4f8c9b4c913"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.10+0/aws_c_http_jq.v0.10.10.x86_64-w64-mingw32.tar.gz"
