[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "fbe9333c8350a649cd4029abfd4966047157f7bb"
os = "macos"

    [[aws_c_http_jq.download]]
    sha256 = "303432d9dde4f95ec5399f9c70700e2d71121260ebcf385aafac35f2f0a9c7bb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.aarch64-apple-darwin.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "34519b85c3db89852f1c3dc051f4de7931897596"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "6471af6e4f0fd5721e8b860a561a2711de1f7bdcaf060d02f624c28cad6d0d14"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.aarch64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "9b18420bd04a877bea68d26301087c525482ae57"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "9598173f4202cf91800e76ffa72168c5e5b8f7547aa593722a9ab855157be65a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.aarch64-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "93984e99ab6152ee9dc476b97aeeff8b17e8f4b3"
os = "freebsd"

    [[aws_c_http_jq.download]]
    sha256 = "211fff8f10e8f28a05e774fcb246fe7f4cf70d93eb6fc22ff7d2f1b72601a472"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.aarch64-unknown-freebsd.tar.gz"
[[aws_c_http_jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05e6e3763da08ebf800e572a28958eabf9ec1b96"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "449a80db0456a7f7593475c900a3f930b696cdf85e019d4a7d01e982af6576d2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8380d96903dfe0fd6a351e94ab3fda16c4e8ce54"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "eed2f80517666d9e41268cb1216df9defa570a1644b3eafdcb2782415a30897b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.armv6l-linux-musleabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a1f1f06b4dad87f0700f9445cbaee4a978a4a5fd"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "c33366854670c8e005bab19f165176af6e3ed3aa56e1a347fe8b88fc8a6ebca3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "141284fd8ca9aebfb908f2f61eeffa6508656eb4"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "cef05228b792e6340fa1a316f06c54f700dfac668ce0f718c789788bde1cda19"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.armv7l-linux-musleabihf.tar.gz"
[[aws_c_http_jq]]
arch = "i686"
git-tree-sha1 = "c6f4f995b825ecc9ec8f6cbbf9970023561c26a3"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "0761aefaef41787307aa0b73fcea92039a3eb5f747b93b4b6cc40245c5220ecb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.i686-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "i686"
git-tree-sha1 = "9f3e636c5b2e149c0548a51a18aa634fe506ff38"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "68f9cc57c5830ed71876e98826877b11710149fd050db29afc5f7a221e31b02d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.i686-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "powerpc64le"
git-tree-sha1 = "525cccd568b6321b9d68d4da3decf8a7412182df"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "a92e4f87a750bfdebabc60d4e0ce8ad38fc582cf61556dd367131927a1e2b42b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.powerpc64le-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "riscv64"
git-tree-sha1 = "c995190b96167afbf5b04399d6af06e2352e7e61"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "de84e52d87e5621b98c98c7cdea63faddcfafa39418a42a32d45085d9eb27629"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.riscv64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "f586ac8c1deaafa08e4e5eaf5c552b7aa4af11dd"
os = "macos"

    [[aws_c_http_jq.download]]
    sha256 = "1567f34f2e5f94c33d99eb5fa75a6f67a6e59351ee4bb1b96d33ad2837af012d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.x86_64-apple-darwin.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "55000ff02c88226ce499cb49253a95e12600fc05"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "250527aad57622d48df052e78b0b07346527daa10cf6f9015f20e39ceb8ca7d0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.x86_64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "7380bc95f2a19637bf872b7dc5f9edcc7da6c18e"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "732f85187b903c5bdd256ddbb4d558d299aa36d345cfb5acc0043e0a7e9a6ff9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.x86_64-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "19258fbcc47a2061789a7583fad2fb2e55c42ac8"
os = "freebsd"

    [[aws_c_http_jq.download]]
    sha256 = "b698473ccb209f4152e8b0be1a70e0ad73974705c4675249a44bdf6ca3034de2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.x86_64-unknown-freebsd.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "f679df6a15b7531adcc59b805b9bfc4f5d158662"
os = "windows"

    [[aws_c_http_jq.download]]
    sha256 = "c7838091ef3e2ddf1c55d54a748d6cefac4eeb6a03ebc8028a1db2e142cbef8b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.12+0/aws_c_http_jq.v0.10.12.x86_64-w64-mingw32.tar.gz"
