[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "0d28826fb1a56b71a4d4429d58e8bcd2ec0be411"
os = "macos"

    [[aws_c_http_jq.download]]
    sha256 = "0c8ce62bc12aa64b8c2ac0aeb0e82e4d0854d07b814f1894d5fb2b1b2dccd78b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.aarch64-apple-darwin.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "e898d1c22ef6a4f353d926d25d27f50221c640bc"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "4430ee45aabeea0652da87379fa57f81f45ca57cf4de82fc1a4a9346df7d1136"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.aarch64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "a86a27011ffd1812ae57685cd48203eb54ed72f0"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "497b2aebe7b661f503ceb61ec10c4a8a1ccbc881aed98c79a93fa7384093647d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.aarch64-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "aarch64"
git-tree-sha1 = "c8a69e3df5efdeef127a5529df041dc16880d422"
os = "freebsd"

    [[aws_c_http_jq.download]]
    sha256 = "5f78cb89f4cddc1c4d43ca0e3202c062d4ef2ad651290d9932f4f83f8559b4b6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.aarch64-unknown-freebsd.tar.gz"
[[aws_c_http_jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e053d28848eb302ab6c2b1a6808844268c0fbc51"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "688f732c2c4d6bb5b9fd68e52e7b76993325a9e2d958e0175942bab58d661733"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "afa455e12fe5c516df0d9c323601304d69b4cb55"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "a9185552d4ea1dc2301f498d0518fb1e3de67344df76ddd0f9bc1141a482efd4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.armv6l-linux-musleabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94d836c4148bc2cffbd968d0b2c633c6679c56f4"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "f84bf44f2671c3cb9a0b2d35a8972554a1f8ba6f622d1c6b7ef0d618878f940a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_http_jq]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef293029f998e93e2f18fff7b1288b01ef44f531"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "98a966ddca6039f5e856c03dd905529bdc01172fe8004bcafa4316ee5cad2adc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.armv7l-linux-musleabihf.tar.gz"
[[aws_c_http_jq]]
arch = "i686"
git-tree-sha1 = "79f213f84b339b7977b4b1cfd5d3b6c7a187773e"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "28ca78452e5fe4daca7c47025ea83d5f1c8a30f1bceab9b64b272f54d65e6e4e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.i686-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "i686"
git-tree-sha1 = "b06e037250ea4a00db78f900465752841a20eac3"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "c8e87f0c98d33df1e581248eaf810c4db4c49a24a51ce718a664ac72b9bb3274"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.i686-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "powerpc64le"
git-tree-sha1 = "16e8d12c11c91bfaff5668ab8bd7ea09808f5995"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "12e0330d18bd18ec46b3376823366b7b3afc42647c775ae40e001635eb02ad74"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.powerpc64le-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "riscv64"
git-tree-sha1 = "bf8b7fc21ef2dde1a3514bd845d06842993735e2"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "88f24b971dd70b68483ba08a53dbb52eb1f39e1982f65c1e209954d852c8a6b4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.riscv64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "869722a43b6643688aca2cc45a01dfd1c1dc16e9"
os = "macos"

    [[aws_c_http_jq.download]]
    sha256 = "8f5b31b7477261ddfb0311ff2f61a4ab6cb2e75d0ec7cff145232d603664813a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.x86_64-apple-darwin.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "69eb37bc3ffc761130667eb55a3495ab804666d5"
libc = "glibc"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "9b78abd72a2c1c9b7f7faba067e46dcb28942305f4e5f4eeca6519b1e54ac03f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.x86_64-linux-gnu.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "f8fe60d489a92dfc60117e82fba851ce70671139"
libc = "musl"
os = "linux"

    [[aws_c_http_jq.download]]
    sha256 = "b8757b9ed77fc20c71e58e8781d79e421a2beedba3c11512b6a185c874507865"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.x86_64-linux-musl.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "f653711da57f79690198a84cd78733351dd38746"
os = "freebsd"

    [[aws_c_http_jq.download]]
    sha256 = "c74eb706ee9e7b5dac219de5788f33e9db347693a73a3800d34ddc7daa8cd1f0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.x86_64-unknown-freebsd.tar.gz"
[[aws_c_http_jq]]
arch = "x86_64"
git-tree-sha1 = "bb1693baae70ee10fb6e4d01d836791491ac103f"
os = "windows"

    [[aws_c_http_jq.download]]
    sha256 = "eacdcf3849b8e408e1ee680bcc87367e73f5f651da9e1e87c1b694733c0ddfb6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jq_jll.jl/releases/download/aws_c_http_jq-v0.10.11+0/aws_c_http_jq.v0.10.11.x86_64-w64-mingw32.tar.gz"
