# Autogenerated wrapper script for aws_c_http_jq_jll for x86_64-w64-mingw32
export libaws_c_http_jq

using aws_c_compression_jll
using aws_c_io_jll
JLLWrappers.@generate_wrapper_header("aws_c_http_jq")
JLLWrappers.@declare_library_product(libaws_c_http_jq, "libaws-c-http.dll")
function __init__()
    JLLWrappers.@generate_init_header(aws_c_compression_jll, aws_c_io_jll)
    JLLWrappers.@init_library_product(
        libaws_c_http_jq,
        "bin\\libaws-c-http.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
